
project: 
  type: website
  output-dir: _site

website: 
  title: "Formation en Data Science et Stress test pour la BCC"
  navbar:
    background: primary
    search: false
    left: 
      - text: "Introduction générale"
        href: qmds/index.qmd
      - text: "Jour 1"
        href: qmds/j1.qmd
      - text: "Jour 2"
        href: qmds/j2.qmd
      - text: "Jour 3"
        href: qmds/j3.qmd
      - text: "Jour 4"
        href: qmds/j4.qmd
      - text: "Jour 5"
        href: qmds/j5.qmd


   
# ----- Execution ------
execute:
  echo: true
  warning: false
  message: false
  cache: false

bibliography: ["references.bib"]